In [1]:
import numpy as np

In [2]:
a = np.uint8([[1, 2, 3],
            [4, 5, 6]])
b = np.uint8([[7, 8, 9],
            [10, 11, 12]])

In [3]:
print('Append')
c = np.append(a, b)
print(c.shape)
print(c)

Append
(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
print('Append 0')
c = np.append(a, b, 0)
print(c.shape)
print(c)

Append 0
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
print('Append 1')
c = np.append(a, b, 1)
print(c.shape)
print(c)

Append 1
(2, 6)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [6]:
print('Concatenate 0')
c = np.concatenate((a, b), axis=0)
print(c.shape)
print(c)

Concatenate 0
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print('Concatenate 1')
c = np.concatenate((a, b), axis=1)
print(c.shape)
print(c)

Concatenate 1
(2, 6)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [8]:
print('Stack 0')
c = np.stack((a, b), axis=0)
print(c.shape)
print(c)

Stack 0
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
print('Stack 1')
c = np.stack((a, b), axis=1)
print(c.shape)
print(c)

Stack 1
(2, 2, 3)
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [10]:
print('Stack 2')
c = np.stack((a, b), axis=2)
print(c.shape)
print(c)

Stack 2
(2, 3, 2)
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
